[project]
name = "python-project"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.3",
    "django-cors-headers>=4.7.0",
    "faiss-cpu>=1.11.0",
    "hf-xet>=1.1.5",
    "huggingface-hub==0.33.2",
    "openvino==2025.2.0",
    "openvino-genai==2025.2.0.0",
    "pypdf>=3.0.1",
    "python-dotenv>=1.1.0",
    "sentence-transformers>=4.1.0",
    "torch>=2.7.1",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]


[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
